#ifndef FRAMELESSWINDOW_GLOBAL_H
#define FRAMELESSWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRAMELESSWINDOW_LIBRARY)
#define FRAMELESSWINDOW_EXPORT Q_DECL_EXPORT
#else
#define FRAMELESSWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // FRAMELESSWINDOW_GLOBAL_H
